### ISSUE TITLE
[FEATURE] Add custom threat rules

### ISSUE THREAD

**Issue by dwisiswant0** [kitabisa/teler#187]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
e.g.
```yaml
    customs:
      - name: Large File Upload
        condition: AND
        rules:
          - element: body_bytes_sent
            pattern: \d{6,}

          - element: request_method
            pattern: P(OST|UT)
```

**Describe alternatives you've considered**

**Additional context**
