### ISSUE TITLE
[BUG] Error! open internal/alert/template/telegram.tmpl: no such file or directory

### ISSUE THREAD

**Issue by PoundXI** [kitabisa/teler#296]
**Describe the bug**
Not send slert to telegram

**To Reproduce**
Just run teler with docker 
```sh
tail -f $PWD/access.log | sudo docker run -i --rm -v $PWD/teler.yaml:/teler.yaml -e TELER_CONFIG=/teler.yaml kitabisa/teler
```
or binary
```sh
tail -f ./access.log | teler -c ./teler.yaml
```
then got error:
> [ERR] Error! open internal/alert/template/telegram.tmpl: no such file or director

```yaml
log_format: |
    <format>

....
....

alert:
  active: true
  provider: "telegram"

notifications:
  telegram:
    token: "<token>"
    chat_id: "<chat_id>"
```

**Expected behavior**
I think it should send alert to telegram

**Screenshots**
![image](https://user-images.githubusercontent.com/4828215/214608404-698554dc-a061-4091-8d2b-201afe526fe1.png)

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- OS version: Linux pg-laptop 5.15.0-58-generic <span>#</span>64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- teler Version v2.0.0-dev.2
