### ISSUE TITLE
[BUG] Not send any alerts to discord

### ISSUE THREAD

**Issue by PoundXI** [kitabisa/teler#297]
**Describe the bug**
Not send any alerts to discord

**To Reproduce**
Just run teler with docker 
```sh
tail -f $PWD/access.log | sudo docker run -i --rm -v $PWD/teler.yaml:/teler.yaml -e TELER_CONFIG=/teler.yaml kitabisa/teler
```
Everything works fine. but no alerts.

```yaml
log_format: |
    <format>

....
....

alert:
  active: true
  provider: "discord"

notifications:
  discord:
     webhook: "https://discord.com/api/webhooks/XXXXXXXXX/AAA-BBB-CCC" << generated from discord webhook UI
     token: "AAA-BBB-CCC"
     channel: "<copied from discord UI in developer mode>"
     color: "16312092"
```

**Expected behavior**
I think it should send alert to discord

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- OS version: Linux pg-laptop 5.15.0-58-generic <span>#</span>64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- teler Version v2.0.0-dev.3
