### ISSUE TITLE
[BUG] cannot disable dashboard

### ISSUE THREAD

**Issue by jazzl0ver** [kitabisa/teler#384]
Dashboard is disabled in the config but still running:
```yaml
...
dashboard:
  active: false
  host: "localhost"
  port: 9080
  username: "wew"
  password: "w0w!"
  endpoint: "/events"
...
```

```
# tail -F /var/log/httpd/access_log | ./teler -c ./teler.example.yaml

          __      __
         / /____ / /__ ____
        / __/ -_) / -_) __/
        \__/\__/_/\__/_/
                        v2.0.0-rc.4

        infosec@kitabisa.com

[WRN] This tool is under development!
[WRN] Please submit a report if an error occurs.
[INF] Analyzing...
[INF] Listening dashboard on http://localhost:9080
```

To make sure it's indeed running:
```
# curl http://localhost:9080
Unauthorized
```
