### ISSUE TITLE
[BUG] Regex not matching Slack token

### ISSUE THREAD

**Issue by markustenghamn** [kitabisa/teler#57]
**Describe the bug**

The regex which validates Slack tokens expects the third part of the token to be exactly 12 digits. However, I generated a token via Slack which has 13 digits. I run my command like this:

```
tail -f -n300 /var/log/caddy.log | teler -c ~/teler.yml
```

I receive the following error.

```
[ERR] Error! Only validates token; please check your config file
[INF] Use "-h" flag for more info about command.
Terminated
```

**To Reproduce**

Go to Slack and create a new bot at (yourworkspace).slack.com/apps/manage/custom-integrations
Then try to use the new token in your yml configuration.

```yaml
log_format: |
  $remote_addr - $remote_user [$time_local] "$request_method $request_uri $request_protocol" $status $body_bytes_sent

alert:
  active: true
  provider: "slack"

notifications:
  slack:
    token: "xoxb-nnnnnnnnnnn-nnnnnnnnnnnnn-XXXXXXXXXXXXXXXXXXXXXXXX"
    color: "#ffd21a"
    channel: "XXXXXXXXXXX"
```

**Expected behavior**

I expected the Slack token to be accepted as a valid token.

**Environment (please complete the following information):**

- OS: linux
- OS version: Linux Ubuntu-1604-xenial-64-minimal 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- teler Version: teler 0.0.4-dev

**Additional context**

I believe the issue is the regex found here https://github.com/kitabisa/teler/blob/f0f8ed54399dd938f77778e89b70001d03aa9703/pkg/matchers/patterns.go#L4 

I think the `d{12}` should be changed to `d{12,13}`.
