### ISSUE TITLE
[BUG][ASK] : teller can not be run message "analyzing" appears

### ISSUE THREAD

**Issue by Anggi17** [kitabisa/teler#77]
**Describe the bug**

when I run the command tail -f /var/log/apache2/access.log | teler -c /var/www/html/teler/teler.yaml -x 25 but the response from teler analyzing is not complete

**To Reproduce**

tail -f /var/log/apache2/access.log | teler -c /var/www/html/teler/teler.yaml -x 25

```yaml
# To write log format, see https://github.com/kitabisa/teler#configuration
log_format: |
  $remote_addr - [$remote_addr] $remote_user - [$time_local] 
  "$request_method $request_uri $request_protocol" $status $body_bytes_sent 
  "$http_referer" "$http_user_agent" $request_length $request_time 
  [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id
rules:
  cache: true
  threat:
    excludes:
      - "Common Web Attack"
      - "CVE"
      - "Bad IP Address"
      - "Bad Referrer"
      - "Bad Crawler"
      - "Directory Bruteforce"

    # It can be user-agent, request path, HTTP referrer, IP address and/or request query values parsed in regExp
    whitelists:
      # - "(curl|Go-http-client|okhttp)/*"
      # - "^/wp-login\\.php"
      # - "https://www\\.facebook\\.com"
      # - "192\\.168\\.0\\.1"

# prometheus:
  # active: false
  # host: "localhost"
  # port: 9099
  # endpoint: "/metrics"

alert:
  active: true
  provider: "slack"

notifications:
  slack:
    token: "xxxxxxxxxx"
    color: "#ffd21a"
    channel: "teler"

 # telegram:
   # token: "123456:ABC-DEF1234...-..."
   # chat_id: "-111000"

 # discord:
   # token: "NkWkawkawkawkawka.X0xo.n-kmZwA8aWAA"
   # color: "16312092"
   # channel: "700000000000000..."
```
**Screenshots**

https://drive.google.com/file/d/1vvbFHk9e-AVJgzUhIeaLynskmG24jYeT/view?usp=sharing

**Environment (please complete the following information):**

- OS: linux
- OS version: Linux kali 5.7.0-kali1-amd54 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
- teler Version : teler 1.0.1
